### PR TITLE
merge upstream

### PR DESCRIPTION
**Pull request by itszootime**

### CODE REVIEW

**Comment by maprost** [comment]
I insert a little hack to make travis build the project.

Inside `Shopify/sarama`, they change the Makefile, so every package is now tested (not only the root one, which makes sense). With this, travis is not building anymore, It can not find the package `github.com/Shopify/sarama` which is correct. I decided as a short version to rename inside the travis build all `github.com/Shopify/sarama` imports into `github.com/remerge/sarama`, so the project is buildable.

**Review by gburanov — CHANGES_REQUESTED** [review]
it generally looks nice, but 1 comment: In this case squashing commits in a bad idea, so can u instead quash just your "trigger build" and name it appropriately?

**Comment by maprost** [comment]
sorry wrong button

**Comment by maprost** [comment]
@gburanov How can I squatch only my last commits?

**Comment by gburanov** [comment]
This is closed in favor of https://github.com/remerge/sarama/pull/15

**Pull request closed without merging**
